### ISSUE TITLE
yandex.ru/images should not show the buttons

### ISSUE THREAD

**Issue by vitaly-zdanevich** [kuanyui/EngineSwitcher#19]
![image](https://github.com/kuanyui/EngineSwitcher/assets/3514015/41827a28-04a8-49df-a86a-a408546004b6)

**Comment by kuanyui** [comment]
Why?? I use this frequently.

2024年3月8日(金) 20:04 Vitaly Zdanevich ***@***.***>:

**Comment by vitaly-zdanevich** [comment]
Images part? But it will not copy the image to Wikipedia, for example.

**Comment by kuanyui** [comment]
Same keyword, it's very useful. I rely on it frequently.

2024年3月8日(金) 21:55 Vitaly Zdanevich ***@***.***>:

**Comment by kuanyui** [comment]
In fact, in the beginning I was designing this WebExtension, I even have considered how to make drop menu for each engine, for example:
- DuckDuckGo: Web, Images, Video, News, Map
- Bing: Web, Images, Video, News, Map
....etc

But this will make the code and UI too complex so I discarded this thought.
